apiVersion: v1
kind: Service
metadata:
  name: chess-explainer
  namespace: chess-explainer
spec:
  selector:
    app: chess-explainer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
